name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - run: git ls-remote
      - name: Checkout head and target branches
        if: ${{ github.base_ref }}
        run: |
          git fetch --no-tags --depth=1 origin ${{ github.base_ref }}
          git fetch --no-tags --depth=1 origin ${{ github.head_ref }}
          # get the actual source for two branches
          git checkout origin/${{ github.base_ref }}
          git checkout origin/${{ github.head_ref }}
          # get back to the merge commit
          git checkout ${{ github.sha }}
      - name: All changed files 🗂
        if: ${{ github.base_ref }}
        run: git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }}

      - name: npm install, build and lint
        run: |
          npm install
          npm run build --if-present
          npm run lint --if-present
      - name: Test Changed Strategies
        if: ${{ github.base_ref }}
        run: |
          CHANGED_STRATEGIES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- src/strategies/)
          if [ -n "$CHANGED_STRATEGIES" ]; then
            echo "Running tests for changed strategies"
            npm run test --filesChanged="$CHANGED_STRATEGIES"
          fi
